###############################################################################
#                         nginx reverse proxy                                 #
###############################################################################
version: "3.7"

services:
  reverse:
    networks:
    - ${STACK_PREFIX}_default

    container_name: reverse
    hostname: reverse
    image: nginx
    environment:
      - BASE_HOSTNAME=${BASE_HOSTNAME}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx
      - ./privatessl:/etc/ssl/private
      - log-disk:/var/log/nginx

networks:
  fasterj_default:
    external: true

volumes:
    log-disk:
      name: ${STACK_PREFIX}_log-disk
      external: true
