###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"

services:
  reverse:
    networks:
    - fasterj_default

    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx
      - ./privatessl:/etc/ssl/private

networks:
  fasterj_default:
    external: true
