###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
  memcached:
    image: memcached:alpine
    container_name: fasterj-memcached

  mailhog:
    image: mailhog/mailhog:latest
    container_name: fasterj-mailhog
    ports:
      - "8081:8025"

  redis:
    image: redis:alpine
    container_name: fasterj-redis

  mariadb:
    image: mariadb:10.4
    container_name: fasterj-mariadb
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=badPurpl310
      - MYSQL_DATABASE=fasterj
      - MYSQL_USER=fasterj
      - MYSQL_PASSWORD=d@mpApple82
    ports:
      - "8083:3306"

  webserver:
    image: nginx:alpine
    hostname: webserver

    container_name: fasterj-webserver
    working_dir: /application
    volumes:
        - .:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8080:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: fasterj-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
