###############################################################################
#                          PHP nginx mariadb phpmyadmin                       #
###############################################################################
version:            "3.1"
services:
  webserver:
    image:          nginx:alpine
    hostname:       webserver
    container_name: ${STACK_PREFIX}-webserver
    working_dir:    /application
    volumes:
        - .:/application
        - ./settings/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./logs/nginx:/var/log/nginx

  memcached:
    image:          memcached:alpine
    container_name: ${STACK_PREFIX}-memcached

  phpmyadmin:
    image:          phpmyadmin/phpmyadmin
    container_name: ${STACK_PREFIX}-phpmyadmin
    environment:
     - PMA_ARBITRARY=1
     - PMA_ABSOLUTE_URI=http://s10.tmg.it/phpmyadmin
     - PMA_HOST=mariadb
    restart:        always
    volumes:
     - /sessions

  mariadb:
    image:          mariadb:10.4
    container_name: ${STACK_PREFIX}-mariadb
    working_dir:    /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${STACK_PREFIX}
      - MYSQL_USER=${STACK_PREFIX}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8083:3306"

  php-fpm:
    build:          phpdocker/php-fpm
    container_name: ${STACK_PREFIX}-php-fpm
    working_dir:    /application
    volumes:
      - .:/application
      - ./settings/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
