###############################################################################
#                          PHP nginx mariadb phpmyadmin                       #
###############################################################################
version:            "3.1"
services:
  webserver:
    image:          nginx:alpine
    hostname:       webserver
    container_name: ${STACK_PREFIX}-webserver
    working_dir:    /application
    environment:
      - BASE_HOSTNAME:${BASE_HOSTNAME}
    volumes:
      - .:/application
      - ./settings/nginx/:/etc/nginx/
      - log-disk:/var/log/nginx

  memcached:
    image:          memcached:alpine
    container_name: ${STACK_PREFIX}-memcached

  mariadb:
    image:          mariadb:10.4
    container_name: ${STACK_PREFIX}-mariadb
    working_dir:    /application
    volumes:
      - .:/application
      - log-disk:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${STACK_PREFIX}
      - MYSQL_USER=${STACK_PREFIX}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8083:3306"

  php-fpm:
    build:          settings/php-fpm
    container_name: ${STACK_PREFIX}-php-fpm
    working_dir:    /application
    volumes:
      - .:/application
      - ./settings/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

volumes:
    log-disk:
